name: html_editor_plus_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  chewie: ^1.10.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  path: ^1.9.0
  pointer_interceptor: ^0.10.1+2
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1
  video_player: ^2.9.3
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.18.3
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5


flutter:
  plugin:
    platforms:
      android:
        default_package: html_editor_plus_package
      ios:
        default_package: html_editor_plus_package
      web:
        default_package: html_editor_plus_package
  assets:
      - packages/html_editor_plus_package/assets/camera_roll_icon.png
      - packages/html_editor_plus_package/assets/h1_dark.png
      - packages/html_editor_plus_package/assets/h2_dark.png
      - packages/html_editor_plus_package/assets/edit_table.png
      - packages/html_editor_plus_package/assets/insert_table.png
      - packages/html_editor_plus_package/assets/delete_column.png
      - packages/html_editor_plus_package/assets/delete_row.png
      - packages/html_editor_plus_package/assets/delete_table.png
      - packages/html_editor_plus_package/assets/insert_column_left.png
      - packages/html_editor_plus_package/assets/insert_row_above.png
      - packages/html_editor_plus_package/assets/insert_row_below.png
      - packages/html_editor_plus_package/assets/insert_column_right.png
      - packages/html_editor_plus_package/assets/scripts/quill_2.0.0_4_min.js
      - packages/html_editor_plus_package/assets/scripts/custom_imageBlot.js
      

